### ISSUE TITLE
父文档名称最后带空格，子文档不会生成

### ISSUE THREAD

**Issue by Zkffkah** [siyuan-note/oceanpress#1]
父文档名称最后带空格，子文档不会生成

**Comment by 2234839** [comment]
这应该是文件系统不支持的文件名，我会考虑以后加入对于非法文件名进行转换的选项。


但目前我正在旅游，所以短期内无法实现，你可以先修改文档名称



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 晚上9:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/oceanpress] 父文档名称最后带空格，子文档不会生成 (Issue #1)




 
父文档名称最后带空格，子文档不会生成

**Comment by 2234839** [comment]
此问题我所考虑的处理方案为：

- 抛出一个错误，提示用户将不会输出此文件
- 不会影响其他文档的输出

理由：

对文件名进行转换然后输出这是不符合用户直觉的，直接告所用户该文件无法创建

---

在下一个版本将实装此处理方案并关闭此 issue, 欢迎继续讨论可行方案。
